disabled_rules:
- trailing_whitespace # 余分に改行がある方が視認性が上がる為、無効
- type_name # クラス名は長くして情報を詰めておく必要もある為、無効
# - opening_brace         # prefer Allman-Style
- identifier_name
- shorthand_operator
- nesting
- function_body_length # 関数の長さ
- cyclomatic_complexity # Ifやswitchの多さを制限する為(10 or less個)、無効
- large_tuple
# ルール一覧を表示
#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- variable_name_max_length
#- variable_name_min_length
#- type_body_length
#- variable_name

# 一行の文字列制限を100文字から300文字に変更
line_length: 300

# 変数名の最大文字数
variable_name_max_length:
- 60 # warning
- 80 # error

# 変数名の最小文字数
variable_name_min_length:
- 1 # warning
- 0 # error

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods
- CommandLineTool
