use_frameworks!

target 'DKMacLibrary_Example' do
  pod 'DKMacLibrary', :path => '../'

  target 'DKMacLibrary_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
