use_frameworks!
platform :osx, '10.12'
target 'DKMacLibrary_Example' do
  pod 'DKMacLibrary', :path => '../'
  pod 'SwiftLint'
  
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  target 'DKMacLibrary_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.2'
  end
end
